name: Gerar APK Automaticamente
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v6

      - name: Configurar Node.js v22
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Instalar Capacitor
        run: npm install @capacitor/cli @capacitor/android @capacitor/local-notifications

      - name: 🧹 Remove pasta Android antiga para evitar conflitos
        run: rm -rf ./android

      - name: Adiciona plataforma Android nova
        run: npx cap add android

      - name: 📡 Sincroniza apenas configurações, sem arquivos locais
        run: npx cap sync android --no-copy

      - name: Configurar Java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Permitir execução do Gradle
        run: chmod +x ./android/gradlew

      - name: Gerar APK
        run: cd android && ./gradlew assembleDebug

      - name: Disponibilizar APK para download
        uses: actions/upload-artifact@v5
        with:
          name: Tapicuz-Admin-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk